In [2]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense

In [4]:
### loading the data
(X_train, y_train), (X_test, y_test) =mnist.load_data()

11490434/11490434 [==============================] - 20s 2us/step


In [5]:
X_train = X_train.reshape((X_train.shape[0]), X_train.shape[1],X_train.shape[2],1)

In [6]:
X_test = X_test.reshape((X_test.shape[0]), X_test.shape[1],X_test.shape[2],1)

In [7]:
### checking the shape
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [8]:
### Normalize the pixel values
X_train = X_train/255
X_test = X_test/255

In [9]:
print(X_train)
print(X_test)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [10]:
print(y_train)
print(y_test)

[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [19]:
#defining model
model=Sequential()
#adding convolution layer
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)))
#adding pooling layer
model.add(MaxPool2D(2,2))
#adding fully connected layer
model.add(Flatten())
model.add(Dense(100,activation='relu'))
#adding output layer
model.add(Dense(10,activation='softmax'))
#compiling the model
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
#fitting the model
model.fit(X_train,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 13s 7ms/step - loss: 0.1575 - accuracy: 0.9529
Epoch 2/10
1875/1875 [==============================] - 13s 7ms/step - loss: 0.0527 - accuracy: 0.9843
Epoch 3/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0342 - accuracy: 0.9893
Epoch 4/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0229 - accuracy: 0.9930
Epoch 5/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0153 - accuracy: 0.9949
Epoch 6/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0110 - accuracy: 0.9962
Epoch 7/10
1875/1875 [==============================] - 16s 9ms/step - loss: 0.0089 - accuracy: 0.9972
Epoch 8/10
1875/1875 [==============================] - 16s 8ms/step - loss: 0.0063 - accuracy: 0.9979
Epoch 9/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0054 - accuracy: 0.9983
Epoch 10/10
1875/1875 [==============================] - 14s 8ms/step - l

In [21]:
### EVALUATING THE MODEL
model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0513 - accuracy: 0.9870


[0.05128614604473114, 0.9869999885559082]